### PR TITLE
Renaming clean up

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)

### CODE REVIEW

**Comment by Eb-Zeero** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[schema/partner.py, line 4 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9UKdRDGTPmyPTn5c6:-LCcoIgv7FSFSucx2ljc:b-cj9gt8) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We clearly missed this when discussing the schema...

* for_semester should be semester
* Allocated_... should be allocated_...
* AllocatedTime arguably should be TimeAllocation
* used_p0_and_p1 should not be part of this type

Maybe have

TimeAllocation:
    p0_and_p1
    p2
    p3

and

TimeUse (or TimeUsage):
    p0_and_p1
    p2
    p3


</blockquote></details>

I did 

class Priority(ObjectType):
    p0_and_p1 = Float()
    p2 = Float()
    p3 = Float()
    p4 = Float()

class TimeAllocation(ObjectType):
    semester = String()
    used_time = Field(Priority)
    allocated_time = Field(Priority)
    science_time = Field(Priority)

---

*[schema/partner.py, line 4 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9dA793wvqSDU1SITW:-LCcpd8cDV5VEfZncygn:b-k3ihn6) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The time allocation probably should not be part of the Partner type.
</blockquote></details>

if this is the case then it should have type partner within it

---

*[schema/partner.py, line 28 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9VMVx0I5zvdy7aGhb:-LCcpyGD5R4DIMsHOUQy:b-dirmeq) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

allocated_time arguably should be allocated_time
</blockquote></details>

this is the same thing

---

*[schema/proposal.py, line 15 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9WI0--BKNU3ytr7sa:-LCcqQ0751wwBEseegdI:bqo64n3) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/proposal.py#L15)):*
> PartnerTimeRequest type
Type partner doesn't have time requests
propobably this might be a bad naming
PartnerTimeRequest => a time a Proposal is requesting from each partner 
TimeAllocation => a time given to a partner

---

*[schema/proposal.py, line 22 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9Wq6ZDTYSC_bHk6lY:-LCcrcrF0Kp8Jez0gmx3:bkrkzma) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/proposal.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

partnerTimeRequests, as its a list?
</blockquote></details>

it might be a bad naming this is a time proposal is requesting from a partner

---

*[schema/target.py, line 4 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9bxtD6inv7hMcSpwH:-LCcuJlNBeMU9EmE_YD5:bk0dunx) ([raw file](https://github.com/saltastro/saltapi/blob/a7fbbdea0e09aabae7679e8ada09fcd6ac129c51/schema/target.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually... How do we cover solar system targets?
</blockquote></details>

I don't know how  they work? but willing to know more about it.
 

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by hettlage** [comment]
schema partners and schema/proposals needs some discussion

---

Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[data/proposal.py, line 43 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC8thED-mnDwbAMpg7S:-LChk56X3FxRvLkcCcE8:b13p9s8) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/data/proposal.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be "partnerTimeRequests", as it's an array?
</blockquote></details>

And why not partner_time_request(s)?

---

*[data/proposal_data/allocations.py, line 21 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChl1yr11gHgAHdWt6T:-LChl1yr11gHgAHdWt6U:b-i32rve) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/allocations.py#L21)):*
> ```Python
> 
> 
> def proposals_allocated_time(semester, proposals):
> ```

The name of the function suggests that it actually returns times. Maybe call it update_time_allocations 

---

*[data/proposal_data/allocations.py, line 54 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChlNRr6gkSVnemuGoz:-LChlNRr6gkSVnemuGp-:bdf00j3) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/allocations.py#L54)):*
> ```Python
>         if proposal in proposals:
>             if tac_comment not in proposals[proposal].tac_comment:
>                 proposals[proposal].tac_comment.append(
> ```

Why is a singular used for allocated_time and tac_comment, even though they are arrays?

---

*[data/proposal_data/requested.py, line 1 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnCe7-8EeW1kBXvcf:-LChlklU0bMH4D43Q7_-:b-o9t8hq) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L1)):*
> ```Python
> import pandas as pd
> ```

You should add docstrings. What are the functions doing?

---

*[data/proposal_data/requested.py, line 24 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnOfV6mqJ46Ycw4yg:-LChnOfV6mqJ46Ycw4yh:b8mmp8c) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L24)):*
> ```Python
>             )
>         )
>     return time_requests
> ```

Probably no need to return the array

---

*[data/proposal_data/requested.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChm1BN0i-7XgESG5GX:-LChm1BN0i-7XgESG5GY:bqypp5h) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L27)):*
> ```Python
> 
> 
> def get_proposals_requested_time(proposal_code_ids):
> ```

I'd avoid using get_ in the function names.

---

*[data/proposal_data/requested.py, line 47 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChn-zD9aqE_3sbUzaW:-LChn-zD9aqE_3sbUzaX:brqxwab) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L47)):*
> ```Python
> 
> 
> def get_requested_per_partner(proposal_code_ids, proposals):
> ```

You are not getting, you are updating, I think.

---

*[data/proposal_data/technical_report.py, line 5 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnnZD23dak2a0M-_h:-LChnnZD23dak2a0M-_i:bqypp5h) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/technical_report.py#L5)):*
> ```Python
> 
> 
> def get_technical_reports(proposal_code_ids):
> ```

I'd avoid using get_ in the function names.

---

*[schema/partner.py, line 4 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9UKdRDGTPmyPTn5c6:-LChoyKk-tcNkAkdhnX-:bqpjgid) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L4)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I did 

class Priority(ObjectType):
    p0_and_p1 = Float()
    p2 = Float()
    p3 = Float()
    p4 = Float()

class TimeAllocation(ObjectType):
    semester = String()
    used_time = Field(Priority)
    allocated_time = Field(Priority)
    science_time = Field(Priority)

</blockquote></details>

This needs some discussion... :)

---

*[schema/partner.py, line 28 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9VMVx0I5zvdy7aGhb:-LChpm7CA8PzxSqDGl6G:bwwka06) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L28)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this is the same thing
</blockquote></details>

Indeed... :D

---

*[schema/partner.py, line 4 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LCho2ZC9d7NArdLw0zc:-LCho2ZC9d7NArdLw0zd:b96ds83) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/schema/partner.py#L4)):*
> ```Python
> 
> 
> class Priority(ObjectType):
> ```

Priority does not imply that this is a time allocation.

---

*[schema/proposal.py, line 15 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9WI0--BKNU3ytr7sa:-LChqGBB8NsZFmIr-La5:b-ynldc4) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/proposal.py#L15)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> PartnerTimeRequest type
Type partner doesn't have time requests
propobably this might be a bad naming
PartnerTimeRequest => a time a Proposal is requesting from each partner 
TimeAllocation => a time given to a partner

</blockquote></details>

I think the naming needs some discussion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28#-:-LChr9FxB3kFvJIiz4cq:b3keop4)*

**Comment by hettlage** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[schema/proposal.py, line 22 at r3](https://reviewable.io/reviews/saltastro/saltapi/28#-LDgUSiFDT7HuLRGYLDL:-LDgUSiFDT7HuLRGYLDM:b-c7uqtr) ([raw file](https://github.com/saltastro/saltapi/blob/c5f3de4aedb4cca0a535f960ec15bad2d40e50d0/schema/proposal.py#L22)):*
> ```Python
> 
> 
> class TimeRequirements(ObjectType):
> ```

Maybe consider calling the class TimeRequirement (singular, not plural) - you can argue that it is the requirement for one semester.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by Eb-Zeero** [comment]
Review status: 15 of 21 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[data/proposal.py, line 43 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC8thED-mnDwbAMpg7S:-LDkYn_1AASok3Feo2q5:b-on642c) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/data/proposal.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And why not partner_time_request(s)?
</blockquote></details>

it is fixed check file data/proposal_data/requested.py

---

*[data/proposal.py, line 160 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9RftzEVr4WLWmWzqP:-LDkZ20vALwN3e5dsQ2y:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/data/proposal.py#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it would be better to be explicit - "PIFirstName" instead of "P1Fname" etc.
</blockquote></details>

Done.

---

*[data/proposal_data/allocations.py, line 21 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChl1yr11gHgAHdWt6T:-LDkZOZP5EtopfXKbs8j:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/allocations.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name of the function suggests that it actually returns times. Maybe call it update_time_allocations 
</blockquote></details>

Done.

---

*[data/proposal_data/allocations.py, line 54 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChlNRr6gkSVnemuGoz:-LDkbIEP9rWMua2ljTBJ:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/allocations.py#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is a singular used for allocated_time and tac_comment, even though they are arrays?
</blockquote></details>

Done.

---

*[data/proposal_data/requested.py, line 24 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnOfV6mqJ46Ycw4yg:-LDko5vm4zyImdFadyTd:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably no need to return the array
</blockquote></details>

Done.

---

*[data/proposal_data/requested.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChm1BN0i-7XgESG5GX:-LDkoG7m747GIGhIcaFH:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd avoid using get_ in the function names.
</blockquote></details>

Done.

---

*[data/proposal_data/requested.py, line 47 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChn-zD9aqE_3sbUzaW:-LDkoL-U-g6AoF3HkYF4:b-bfu3lp) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are not getting, you are updating, I think.
</blockquote></details>

yes I am
Done.

---

*[data/proposal_data/technical_report.py, line 5 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnnZD23dak2a0M-_h:-LDkpMNkAPD8WsLW9JlV:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/technical_report.py#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd avoid using get_ in the function names.
</blockquote></details>

Done.

---

*[schema/partner.py, line 4 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9UKdRDGTPmyPTn5c6:-LDkpPlt2CUYc0-KIDK8:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This needs some discussion... :)
</blockquote></details>

Done.

---

*[schema/partner.py, line 28 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9VMVx0I5zvdy7aGhb:-LDkqJfE9QHzS7qrdt7p:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/partner.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Indeed... :D
</blockquote></details>

Done.

---

*[schema/partner.py, line 4 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LCho2ZC9d7NArdLw0zc:-LDkpWVY3wcgEFrNCFCR:bp3til9) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/schema/partner.py#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Priority does not imply that this is a time allocation.
</blockquote></details>

this was discussed  we agreed that it should be like.
timeAllocations{
    allocatedTime {
        P0andP1, P2, P3
    }
}
Done.

---

*[schema/proposal.py, line 15 at r1](https://reviewable.io/reviews/saltastro/saltapi/28#-LC9WI0--BKNU3ytr7sa:-LDkqfVn3qI9ekgFS24r:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/08bc9a11d4a3450782486a8f6c5d9421e44b69c2/schema/proposal.py#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the naming needs some discussion.
</blockquote></details>

Done.

---

*[schema/proposal.py, line 22 at r3](https://reviewable.io/reviews/saltastro/saltapi/28#-LDgUSiFDT7HuLRGYLDL:-LDkqhb032uJcnF52b76:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/c5f3de4aedb4cca0a535f960ec15bad2d40e50d0/schema/proposal.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe consider calling the class TimeRequirement (singular, not plural) - you can argue that it is the requirement for one semester.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by hettlage** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[run.py, line 260 at r4](https://reviewable.io/reviews/saltastro/saltapi/28#-LDlGsRR-3rTSqTgoeyb:-LDlGsRS1Z_Rzx8LTDnr:bw8flc2) ([raw file](https://github.com/saltastro/saltapi/blob/9a6ca9b32809d405ec6be50acc7c1958a04fc7a0/run.py#L260)):*
> ```Python
> 
> 
> @socketio.on('e')
> ```

If these events are used, they should have meaningful names. Otherwise the code should be removed.

---

*[data/proposal_data/allocations.py, line 54 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChlNRr6gkSVnemuGoz:-LDlJn6k25f5OFU35Tlt:bdo0wka) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/allocations.py#L54)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But allocated_time is still called allocated_time in the code... 

---

*[data/proposal_data/requested.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChm1BN0i-7XgESG5GX:-LDlIYlT64ZwRVzrqrp1:b-6axtmt) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, but "update" seems a bit odd, because you aren't updating anything. Just calling the function "proposals_requested_time" might be a better option.

---

*[data/proposal_data/technical_report.py, line 5 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnnZD23dak2a0M-_h:-LDlJ1Na36c846jBTgwm:bkzmn54) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/technical_report.py#L5)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, but "update" seems a bit odd, because you aren't updating anything. Just calling the function "technical_reports" might be a better option.

---

*[schema/proposal.py, line 22 at r3](https://reviewable.io/reviews/saltastro/saltapi/28#-LDgUSiFDT7HuLRGYLDL:-LDlJEyq6V5mPmhAABZv:b42cswc) ([raw file](https://github.com/saltastro/saltapi/blob/c5f3de4aedb4cca0a535f960ec15bad2d40e50d0/schema/proposal.py#L22)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You say it's done - but the class is still called TimeRequirements... :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by Eb-Zeero** [comment]
Reviewed 1 of 2 files at r5.
Review status: 20 of 21 files reviewed, 6 unresolved discussions (waiting on @hettlage and @Eb-Zeero)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by Eb-Zeero** [comment]
Review status: 13 of 21 files reviewed, 7 unresolved discussions (waiting on @hettlage and @Eb-Zeero)

---

*[run.py, line 260 at r4](https://reviewable.io/reviews/saltastro/saltapi/28#-LDlGsRR-3rTSqTgoeyb:-LFSZJu8EX4qxwWarnjk:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/9a6ca9b32809d405ec6be50acc7c1958a04fc7a0/run.py#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If these events are used, they should have meaningful names. Otherwise the code should be removed.
</blockquote></details>

Done.

---

*[data/proposal_data/requested.py, line 1 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnCe7-8EeW1kBXvcf:-LFSYJKj6NKz0ZuxXN4S:bx4fflk) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should add docstrings. What are the functions doing?
</blockquote></details>

line 65: I I use read_sql

---

*[data/proposal_data/requested.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChm1BN0i-7XgESG5GX:-LFSYTDhAIX8YXOqhAvC:b-kznt58) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks, but "update" seems a bit odd, because you aren't updating anything. Just calling the function "proposals_requested_time" might be a better option.
</blockquote></details>

now it is fill... what would be the most appropriate word

---

*[schema/proposal.py, line 22 at r5](https://reviewable.io/reviews/saltastro/saltapi/28#-LFSU3dLE0HrKu60a3Fu:-LFSU3dLE0HrKu60a3Fv:b-458f4) ([raw file](https://github.com/saltastro/saltapi/blob/1f0e31aaa215d570b69a7f228dea7cf7b4d6bdb1/schema/proposal.py#L22)):*
> TimeRequirements.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by hettlage** [comment]
Reviewed 1 of 2 files at r5, 7 of 7 files at r6.
Review status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @Eb-Zeero)

---

*[data/proposal.py, line 126 at r6](https://reviewable.io/reviews/saltastro/saltapi/28#-LFVFhEd-z2WWQuWEadw:-LFVFhEeD85hvj02Eyiw:b-n8z3yb) ([raw file](https://github.com/saltastro/saltapi/blob/b0b817f2af3ca2edb1c307b84eed0d3de598c67f/data/proposal.py#L126)):*
> ```Python
>     if not public:
>         proposals_text = get_proposals_text(proposal_code_ids)
>         tech_reports = fill_technical_reports(proposal_code_ids)
> ```

That may be me, but "fill_..." perhaps looks a bit odd.

---

*[data/proposal_data/requested.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChm1BN0i-7XgESG5GX:-LFVGcxA9VwFP5-jzd7m:b4jg6i8) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

now it is fill... what would be the most appropriate word
</blockquote></details>

If you are (contrary to what I thought) you're updating, you probably should keep the old name(s) "update_...". BUT: Is there a need to return something then? And you should update the docstring, as you aren't querying 

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by chynamyerz** [comment]
Reviewed 3 of 13 files at r1, 9 of 17 files at r2, 1 of 5 files at r3, 1 of 2 files at r5, 7 of 7 files at r6.
Review status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by Eb-Zeero** [comment]
Review status: 18 of 21 files reviewed, 5 unresolved discussions (waiting on @chynamyerz, @hettlage, and @Eb-Zeero)

---

*[data/proposal_data/requested.py, line 1 at r2](https://reviewable.io/reviews/saltastro/saltapi/28#-LChnCe7-8EeW1kBXvcf:-LFWKd0LCshJhcB6O1P3:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/999e955ba434fb2e08884fd69414503109f0f815/data/proposal_data/requested.py#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

line 65: I I use read_sql
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by Eb-Zeero** [comment]
Review status: 18 of 21 files reviewed, 5 unresolved discussions (waiting on @chynamyerz and @hettlage)

---

*[data/proposal.py, line 126 at r6](https://reviewable.io/reviews/saltastro/saltapi/28#-LFVFhEd-z2WWQuWEadw:-LFWKpWg6hMdAW3E7yZu:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/b0b817f2af3ca2edb1c307b84eed0d3de598c67f/data/proposal.py#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That may be me, but "fill_..." perhaps looks a bit odd.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Comment by chynamyerz** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/28)*

**Pull request merged**
