### PR TITLE
Adding Docker

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 12 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy-SPw12ZlW1iEF3NX:-Nwy-SPw12ZlW1iEF3NY:b-7ac0i3) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L12)):*
> ```Dockerfile
> # Install any needed dependencies specified in requirements.txt
> RUN pip install --no-cache-dir -r requirements.txt
> RUN pip install pandas
> ```

These should be added to the requirements file, if possible. If impossible, you should add a comment explaining it.
___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy-odQD0UmfBDp0bZq:-Nwy-odQD0UmfBDp0bZr:bdqdjx0) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
> ```Dockerfile
> 
> # Command to run the Flask application CMD ["python3", "/app/run.py"]
> CMD ["python3", "/app/run.py"]
> ```

Can you run this as non-root (with the USER command)?
___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-Nwy04Cb0DUgNtnUs0tL:bpgkvzt) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
> ```Dockerfile
> 
> # Command to run the Flask application CMD ["python3", "/app/run.py"]
> CMD ["python3", "/app/run.py"]
> ```

Isn't the CMD command inconsistent with the entry point in the docker compose file? (And why do you have both?)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`Dockerfile` line 12 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy-SPw12ZlW1iEF3NX:-NxBh6ORBkCp1yxnopPm:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These should be added to the requirements file, if possible. If impossible, you should add a comment explaining it.
</blockquote></details>

Done.
___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-NxBhazX9R7laG5pm5JY:b-7ql1td) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't the CMD command inconsistent with the entry point in the docker compose file? (And why do you have both?)
</blockquote></details>

fixed

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy-odQD0UmfBDp0bZq:-NxBhgdH90aN1x_WJjXb:b-7hzkzv) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can you run this as non-root (with the USER command)?
</blockquote></details>

Can I fix this on another PR

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-NxBlH3gDM0yMgWBRPzK:bnj3hbk) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

But you don't need the entry point in the docker compose file, do you, if it's the same?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-NxC3Dr5CS8i5Xo0Wjmx:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you don't need the entry point in the docker compose file, do you, if it's the same?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-NxC9qNG-fafF1eLmkNE:b-ng2cw2) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wouldn't you rather remove the entry-point from the docker compose file?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`Dockerfile` line 21 at r1](https://reviewable.io/reviews/saltastro/saltapi/82#-Nwy04Cb0DUgNtnUs0tK:-NxCCwy98Gy0hoqjzcmc:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/a0a6e0a4ebe1b4171a8c85c66c2bcf469cf0eaed/Dockerfile#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't you rather remove the entry-point from the docker compose file?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 16 at r6](https://reviewable.io/reviews/saltastro/saltapi/82#-NxCGMC6CsOXrhC07I7i:-NxCGMC6CsOXrhC07I7j:b-ib4hcf) ([raw file](https://github.com/saltastro/saltapi/blob/05b06033bf99d24cd74ec3e882363c7ee261430b/Dockerfile#L16)):*
> ```Dockerfile
> EXPOSE 5001
> 
> # Command to run the Flask application CMD ["python3", "/app/run.py"]
> ```

The CMD part should be removed from the comment.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`Dockerfile` line 16 at r6](https://reviewable.io/reviews/saltastro/saltapi/82#-NxCGMC6CsOXrhC07I7i:-NxCGr3jAc5bnOQ4GB7G:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/05b06033bf99d24cd74ec3e882363c7ee261430b/Dockerfile#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The CMD part should be removed from the comment.
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/82)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
