### PR TITLE
updating tac members

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)

### CODE REVIEW

**Comment by hettlage** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[requirements.txt, line 87 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlX9YVCL3O2tEIFkio:-LAlX9YVCL3O2tEIFkip:b-heqsrl) ([raw file](https://github.com/saltastro/saltapi/blob/a61d9c0bbf1f206b313a07e5d3135430971be0d8/requirements.txt#L87)):*
> ```
> WTForms==2.1
> yuicompressor==2.4.8
> uWSGI==2.0.13.1
> ```

Isn't uWSGI required?

---

*[data/user.py, line 133 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlT9YZAkkyAM5jHgIZ:-LAlT9YZAkkyAM5jHgI_:btc1pc1) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L133)):*
> ```Python
> def update_tac_member(partner, member, cursor):
>     """
>     Update a proposal's reviewer.
> ```

The method is adding rather than updating, which should be reflected in the name. And how do you remove a TAC member? How do you add/remove a TAC chair?

---

*[data/user.py, line 138 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlSjq3-ZmpynPVQZfw:-LAlSjq3-ZmpynPVQZfx:b-i4anff) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L138)):*
> ```Python
>     ----------
>     partner : str
>         partner updating member.
> ```

Probably rather: The partner code (such as "RSA") of the partner whose TAC is updated. 

---

*[data/user.py, line 140 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlUPl-4-WvynBTJfQI:-LAlUPl-4-WvynBTJfQJ:b-r8eyzw) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L140)):*
> ```Python
>         partner updating member.
>     member : str
>         username of a member.
> ```

The username of the added/updated TAC member.

---

*[data/user.py, line 151 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlV-Q2D_XoE5W7zlp7:-LAlV-Q2D_XoE5W7zlp8:baoeakq) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L151)):*
> ```Python
>     if not g.user.may_perform(Action.UPDATE_TAC_COMMENTS,
>                               partner=partner):
>         raise InvalidUsage(message='You are not allowed to update members of {partner}'
> ```

"InvalidUsage" might not be the best name. It might make more sense to have a dedicated NotAuthorised exception. Another interesting question is whether the auth checking should be moved elsewhere.

---

*[data/user.py, line 157 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlVW6I-FpUl9xFBXnY:-LAlVW6I-FpUl9xFBXnZ:bze6eo5) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L157)):*
> ```Python
> 
>     sql = '''
>     INSERT INTO PiptUserTAC (PiptUser_Id, Partner_Id, Chair)
> ```

Unless you can update something (such as the chair status), the ON DUPLICATE KEY part might be a bit misleading, as nothing is updated.

---

*[data/user.py, line 173 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlVskz9IkuCkkHlIzb:-LAlVskz9IkuCkkHlIzc:b-5h8nud) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L173)):*
> ```Python
> def update_tac_members(partner, members):
>     """
>     Update the database with a list of members.
> ```

Perhaps rather: Update a partner's TAC with a list of members.

---

*[data/user.py, line 178 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlWnfQ89X3oOjPVTuy:-LAlWnfQ89X3oOjPVTuz:bbsc7gg) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L178)):*
> ```Python
>     ----------
>     partner : str
>        Partner code like "RSA".
> ```

Maybe: The partner code (such as "RSA") of the partner whose TAC is updated. 

---

*[data/user.py, line 180 at r1](https://beta.reviewable.io/reviews/saltastro/saltapi/27#-LAlW2Lc6MAsopB2MN9r:-LAlW2Lc6MAsopB2MN9s:b68e82l) ([raw file](https://github.com/saltastro/saltapi/blob/81dfcb69f4377cdb58fd3c4d6896abf8e93d5869/data/user.py#L180)):*
> ```Python
>        Partner code like "RSA".
>     members : iterable
>         The list of user names of members..
> ```

.. ---> . ; members --> members added to the TAC

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by hettlage** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by Eb-Zeero** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by Eb-Zeero** [comment]
Review status: 2 of 4 files reviewed at latest revision, 16 unresolved discussions.

---

*[run.py, line 137 at r2](https://reviewable.io/reviews/saltastro/saltapi/27#-LAwMxGJE7ylvH724uIo:-LAwYOkz0t1nHE0ofkPD:b-lcjsqi) ([raw file](https://github.com/saltastro/saltapi/blob/26e33b661018bfc7e966e34db1df23c9b9e84f22/run.py#L137)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should use dashes rather than underscores. It's probably more common, and is the convention used for other routes in this file.

The route and the function name should be consistent. The verb should come first.
</blockquote></details>

I when ever I switch to python underscore is in my head I will

---

*[data/user.py, line 213 at r2](https://reviewable.io/reviews/saltastro/saltapi/27#-LAwQTHrAAomT0-ktJqV:-LAwdo7BDDPVcb4iuv5-:b-46t1gc) ([raw file](https://github.com/saltastro/saltapi/blob/26e33b661018bfc7e966e34db1df23c9b9e84f22/data/user.py#L213)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might be ambiguous. Does "update" mean that you replace all the existing TAC members, or that you add new ones?
</blockquote></details>

update which already there or add new once

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by Eb-Zeero** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by hettlage** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[data/user.py, line 174 at r3](https://reviewable.io/reviews/saltastro/saltapi/27#-LBWOpLN2mfzsCHCfwnc:-LBWOpLN2mfzsCHCfwnd:b-yyqwqm) ([raw file](https://github.com/saltastro/saltapi/blob/d15ee56cde2dca5aa0d649a0d227d082382c938f/data/user.py#L174)):*
> ```Python
> def remove_tac_member(partner, member, cursor):
>     """
>     remove a given member as a tac ot the given partner.
> ```

Remove a user as member from a partner's TAC.

---

*[data/user.py, line 209 at r3](https://reviewable.io/reviews/saltastro/saltapi/27#-LBWPE6nB4kOLPl788V3:-LBWPE6nB4kOLPl788V4:b-9uu2vd) ([raw file](https://github.com/saltastro/saltapi/blob/d15ee56cde2dca5aa0d649a0d227d082382c938f/data/user.py#L209)):*
> ```Python
> def update_tac_members(partner, members):
>     """
>     Update members which are already on the database or add new once form the given list for the given partner.
> ```

Add or update a list of members for a partner's TAC.

If a member is not in the database, they are added. Otherwise their details are updated in the database.

---

*[data/user.py, line 216 at r3](https://reviewable.io/reviews/saltastro/saltapi/27#-LBWQJ8_EbMlG2bGnfJf:-LBWQJ8_EbMlG2bGnfJg:brpajdl) ([raw file](https://github.com/saltastro/saltapi/blob/d15ee56cde2dca5aa0d649a0d227d082382c938f/data/user.py#L216)):*
> ```Python
>        Partner code like "RSA".
>     members : iterable
>         The list of user names of members..
> ```

The list of usernames of members, like

---

*[data/user.py, line 240 at r3](https://reviewable.io/reviews/saltastro/saltapi/27#-LBWQybF7itcPNKBVfNe:-LBWQybF7itcPNKBVfNf:b-ntyyz) ([raw file](https://github.com/saltastro/saltapi/blob/d15ee56cde2dca5aa0d649a0d227d082382c938f/data/user.py#L240)):*
> ```Python
> def remove_tac_members(partner, members):
>     """
>     Remove all members from the given list of members from being the tac members of given partner
> ```

Remove a list of members from a partner's TAC.

---

*[data/user.py, line 247 at r3](https://reviewable.io/reviews/saltastro/saltapi/27#-LBWQXjuDgVm3yrb6lzZ:-LBWQXjuDgVm3yrb6lz_:b21cfxz) ([raw file](https://github.com/saltastro/saltapi/blob/d15ee56cde2dca5aa0d649a0d227d082382c938f/data/user.py#L247)):*
> ```Python
>         Partner code like "RSA".
>     members : iterable
>         The list of user names of members.. like [{member: 'user-1'}, {member: 'user-4'}]
> ```

Remove '..'

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by hettlage** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[data/user.py, line 174 at r4](https://reviewable.io/reviews/saltastro/saltapi/27#-LBac32m7H8CstrJnRRj:-LBac32m7H8CstrJnRRk:b-i1yp3l) ([raw file](https://github.com/saltastro/saltapi/blob/2151050e2507426930dc3fbe222faa85660603be/data/user.py#L174)):*
> ```Python
> def remove_tac_member(partner, member, cursor):
>     """
>     Remove a list of members from a partner's TAC.
> ```

list of members --> member

---

*[data/user.py, line 209 at r4](https://reviewable.io/reviews/saltastro/saltapi/27#-LBabwqqD4oPFaccQn3W:-LBabwqqD4oPFaccQn3X:bb5qh6j) ([raw file](https://github.com/saltastro/saltapi/blob/2151050e2507426930dc3fbe222faa85660603be/data/user.py#L209)):*
> ```Python
> def update_tac_members(partner, members):
>     """
>     dd or update a list of members for a partner's TAC.
> ```

'A' missing at the beginning.

---


*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Comment by hettlage** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/27)*

**Pull request merged**
