### PR TITLE
Broken proposals

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7If3I_4c-YpJHwUVHi:-M7If3I_4c-YpJHwUVHj:b-7lr41f) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
> ```Python
> 
> 
> def find_proposals_allocated_time(partner_codes, semester):
> ```

find_proposals_allocated_time ---> find_proposals_with_allocated_time
___
*[data/common.py, line 10 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7IgXJV4ROtohVO7UMg:-M7Ig7Ss-zGVdeEwozoq:bkacoz0) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L10)):*
> ```Python
>     allocated_time_sql = """
> SELECT DISTINCT ProposalCode_Id, Proposal_Code
> FROM MultiPartner
> ```

Don't you have to check that the time allocation is greater than 0?
___
*[data/common.py, line 27 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7IfFBXBL5hqQPszNJv:-M7IfFBXBL5hqQPszNJw:bxp77lu) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L27)):*
> ```Python
> 
> 
> def find_proposals_submitted(partner_codes, semester):
> ```

find_proposals_submitted ---> find_submitted_proposals
___
*[data/common.py, line 72 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7Ieof9EOmRTKEeOPqd:-M7IeofAAK0vfqJSi5BV:b9y8fyo) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L72)):*
> ```Python
>             all_user_proposals.append(str(row["ProposalCode_Id"]))
>     return {
>         'ProposalCode_Ids': all_user_proposals,
> ```

You are returning the same quantity twice.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7Ija2r7DLof_paWhbO:-M7Ija2sDhox7TdIlG0h:b-kuz42v) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
> ```Python
> 
> 
> def find_proposals_allocated_time(partner_codes, semester):
> ```

What about proposals with time requests?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7If3I_4c-YpJHwUVHi:-M7aquRH56GDwWY2sxsB:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

find_proposals_allocated_time ---> find_proposals_with_allocated_time
</blockquote></details>

Done.
___
*[data/common.py, line 10 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7IgXJV4ROtohVO7UMg:-M7aqyU7BGjHQiU00r_A:b3d113m) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Don't you have to check that the time allocation is greater than 0?
</blockquote></details>

no need as we discussed on the salt-api-server
___
*[data/common.py, line 27 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7IfFBXBL5hqQPszNJv:-M7arAMgDnsgVu1ZYhzb:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

find_proposals_submitted ---> find_submitted_proposals
</blockquote></details>

Done.
___
*[data/common.py, line 72 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7Ieof9EOmRTKEeOPqd:-M7arGMAEgOmjY0L9zsk:blcw02q) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are returning the same quantity twice.
</blockquote></details>

notice that 
before statistics were separate they were differn I will change it as well
just need query to be correct before going deep.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7If3I_4c-YpJHwUVHi:-M7bPAdG-7NO4IrAtzig:bjdyomc) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Really? I don't see a change? :)
___
*[data/common.py, line 27 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7IfFBXBL5hqQPszNJv:-M7bP1i_EVl8SVtT96Qp:bjdyomc) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Really? I don't see a change? :)
___
*[data/common.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/61#-M7bPLSx1Rvxz5wBT4bj:-M7bPLSx1Rvxz5wBT4bk:b-mqws04) ([raw file](https://github.com/saltastro/saltapi/blob/c11c32de77f884439672ac2c66892b64ed23f0ea/data/common.py#L27)):*
> ```Python
> 
> 
> def find_proposals_submitted(partner_codes, semester):
> ```

You should add a docstring pointing out that a proposal is included even if the time request is for 0 seconds.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[data/common.py, line 35 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g3-jB9SN6ebkXdYAP:-M7g3-jB9SN6ebkXdYAQ:bo5qcfc) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L35)):*
> ```Python
>     JOIN ProposalStatus USING (ProposalStatus_Id)
>     JOIN MultiPartner USING(ProposalCode_Id)
>     JOIN Semester AS s ON MultiPartner.Semester_Id = s.Semester_Id
> ```

Given that you use aliases for no other table, you arguably shouldn't use an alias for Semester.
___
*[data/common.py, line 52 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g4gkn1yPuei7EM7_n:-M7g4gkn1yPuei7EM7_o:b9bj3np) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L52)):*
> ```Python
> 
> 
> def get_user_proposal_ids(semester, partner_code=None):
> ```

The name get_user_proposal_ids might be misinterpreted as meaning "a user's proposals". So if yiu want to include the user in the name, say get_user_viewable_proposal_ids.
___
*[data/common.py, line 54 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g5mQl9Al7mkVdx4Nx:-M7g5mQl9Al7mkVdx4Ny:b-m3cvni) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L54)):*
> ```Python
> def get_user_proposal_ids(semester, partner_code=None):
> 
>     conn = sdb_connect()
> ```

You should use the get_all_proposal_ids function to get the proposals.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7Ija2r7DLof_paWhbO:-M7giBAu8pfNeONE1TW5:b-s6za08) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about proposals with time requests?
</blockquote></details>

Does the name really matter if we have a docstring explaing what really will be returned.
___
*[data/common.py, line 27 at r2](https://reviewable.io/reviews/saltastro/saltapi/61#-M7bPLSx1Rvxz5wBT4bj:-M7giX6i25zAN26-k83y:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/c11c32de77f884439672ac2c66892b64ed23f0ea/data/common.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should add a docstring pointing out that a proposal is included even if the time request is for 0 seconds.
</blockquote></details>

Done.
___
*[data/common.py, line 35 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g3-jB9SN6ebkXdYAP:-M7gdXW01PGjBsm0ZMq4:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you use aliases for no other table, you arguably shouldn't use an alias for Semester.
</blockquote></details>

Done.
___
*[data/common.py, line 52 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g4gkn1yPuei7EM7_n:-M7gccbV0Vy-DYAJDGFS:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name get_user_proposal_ids might be misinterpreted as meaning "a user's proposals". So if yiu want to include the user in the name, say get_user_viewable_proposal_ids.
</blockquote></details>

Done.
___
*[data/common.py, line 54 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g5mQl9Al7mkVdx4Nx:-M7gdHEI5TW3JL8_GJrl:bs5v2zw) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L54)):*
> get_all_proposal_ids
partner not proposals which is not done correctly at the moment and there is no solution as far.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[data/common.py, line 7 at r1](https://reviewable.io/reviews/saltastro/saltapi/61#-M7Ija2r7DLof_paWhbO:-M7gpTMA0ONmZyKwjjME:b25awt5) ([raw file](https://github.com/saltastro/saltapi/blob/70bc6f7b3af93be45bbb5bfef92b43b9a8a184ab/data/common.py#L7)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Does the name really matter if we have a docstring explaing what really will be returned.
</blockquote></details>

Yes, I strongly believe so. I wouldn't rely on people reading the docstring, so the name should be an accurate reflection of what the function does. (But I'm not sure why you ask?)
___
*[data/common.py, line 54 at r3](https://reviewable.io/reviews/saltastro/saltapi/61#-M7g5mQl9Al7mkVdx4Nx:-M7gsqwyC_1WwYjgF-Qb:b-qxv8is) ([raw file](https://github.com/saltastro/saltapi/blob/9eb532043e821ae11861e23d32dc8a85425eeaef/data/common.py#L54)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> get_all_proposal_ids
partner not proposals which is not done correctly at the moment and there is no solution as far.


</blockquote></details>

Maybe we should have a chat about this then?
___
*[data/common.py, line 45 at r4](https://reviewable.io/reviews/saltastro/saltapi/61#-M7gpz_L9mYPVP2ApcMT:-M7gpz_L9mYPVP2ApcMU:bdalw6i) ([raw file](https://github.com/saltastro/saltapi/blob/33afc76fa33e6c0a87b5ee6727e6397b8545f3ed/data/common.py#L45)):*
> ```Python
> def find_proposals_with_time_requests(partner_codes, semester):
>     """
>     All of the proposal that are requesting time.
> ```

All the proposals that are requesting time.

A proposal is included even if the time request is for 0 seconds.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[data/common.py, line 45 at r5](https://reviewable.io/reviews/saltastro/saltapi/61#-M7mHgdpChx8mfILcSWq:-M7mHgdqEZfhUNyqSdV6:bwwaize) ([raw file](https://github.com/saltastro/saltapi/blob/5e2809705c27cec731f83f816f01780c85e4cf7d/data/common.py#L45)):*
> ```Python
> def find_proposals_with_time_requests(partner_codes, semester):
>     """
>     Alls the proposal that are requesting time.
> ```

Alls the proposal ---> All the proposals

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[data/common.py, line 45 at r4](https://reviewable.io/reviews/saltastro/saltapi/61#-M7gpz_L9mYPVP2ApcMT:-M7lpohl1qQ-bxFMUCYX:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/33afc76fa33e6c0a87b5ee6727e6397b8545f3ed/data/common.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

All the proposals that are requesting time.

A proposal is included even if the time request is for 0 seconds.
</blockquote></details>

Done.
___
*[data/common.py, line 45 at r5](https://reviewable.io/reviews/saltastro/saltapi/61#-M7mHgdpChx8mfILcSWq:-M7qA5i58WRjdXc2Agr6:b-896fix) ([raw file](https://github.com/saltastro/saltapi/blob/5e2809705c27cec731f83f816f01780c85e4cf7d/data/common.py#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Alls the proposal ---> All the proposals
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastro/saltapi/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
